version: "3.7"

services:
  traefik:
    image: traefik:v2.11

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./../traefik-config/traefik.yml:/etc/traefik/traefik.yml
      - ./../traefik-config/dynamic-configuration.yml:/etc/traefik/dynamic-configuration.yml
      - ./../..:/plugins-local/src/github.com/quortex/traefik-responseheadersfilter/

    ports:
      - "8080:80"

  hello:
    image: ealen/echo-server
    labels:
      - traefik.enable=true
      - traefik.http.routers.hello.entrypoints=http
      - traefik.http.routers.hello.rule=Host(`localhost`)
      - traefik.http.services.hello.loadbalancer.server.port=80
      - traefik.http.routers.hello.middlewares=my-traefik-responseheadersfilter@file
